/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Tue Oct 06 16:15:17 2026 */

/* parameterized module instance */
pll_100 __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
